============[Date]============
[ 2021-01-31 12:58:57  Asia/Jakarta ] 
==========[Response]==========
ok:			False
curl_error_code:		6
curl_error:		Could not resolve host: api.telegram.org
=========[Sent Data]==========
[ref]
ref.update_id= 804390441
ref.message.message_id= 10211
ref.message.from.id= 1393342467
ref.message.from.is_bot= false
ref.message.from.first_name= Fadhil
ref.message.from.last_name= Riyanto
ref.message.from.username= fadhil_riyanto
ref.message.from.language_code= en
ref.message.chat.id= 1393342467
ref.message.chat.first_name= Fadhil
ref.message.chat.last_name= Riyanto
ref.message.chat.username= fadhil_riyanto
ref.message.chat.type= private
ref.message.date= 1612072721
ref.message.text= /quran
ref.message.entities.0.offset= 0
ref.message.entities.0.length= 6
ref.message.entities.0.type= bot_command


[ref]
ref.action= typing


============[Trace]===========
#0 C:\bot telegram\vendor\eleirbag89\telegrambotphp\Telegram.php(654): TelegramErrorLogger::log(Array, Array)
#1 C:\bot telegram\vendor\eleirbag89\telegrambotphp\Telegram.php(46): Telegram->sendAPIRequest('https://api.tel...', Array)
#2 C:\bot telegram\vendor\eleirbag89\telegrambotphp\Telegram.php(131): Telegram->endpoint('sendChatAction', Array)
#3 C:\bot telegram\index.php(230): Telegram->sendChatAction(Array)
#4 {main}

